# Generated by Django 3.2.5 on 2021-07-26 19:14

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210726_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default=datetime.datetime(2021, 7, 26, 19, 14, 55, 537767, tzinfo=utc), upload_to='./profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
            preserve_default=False,
        ),
    ]
